USE [maffiox-pis-db]
GO

CREATE TABLE T_Project(
	id				INT				IDENTITY(1,1)	NOT NULL,
	name			VARCHAR(50)						NOT NULL,
	startDate		DATE							NOT NULL,
	CONSTRAINT PK_T_Project PRIMARY KEY CLUSTERED (id ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

CREATE TABLE T_Risk(
	id				INT				IDENTITY(1,1)	NOT NULL,
	idProject       INT                             NULL		DEFAULT(0),
	name			VARCHAR(50)						NOT NULL,
	description		VARCHAR(300)					NOT NULL,
	probability		DECIMAL(3, 2)					NOT NULL,
	priority		DECIMAL(3, 2)					NOT NULL,
	impact			INT								NOT NULL,
	CONSTRAINT PK_T_Risk PRIMARY KEY CLUSTERED (id ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO
